name: Build VSCode Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          npm install -g @vscode/vsce

      - name: Package VSIX
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          npm run build

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plantuml-preview
          path: build/*.vsix
          retention-days: 7
